version: "3.8"

services:
  postgres:
    hostname: db.etms.prod
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  adminer:
    hostname: admin.etms.prod
    depends_on:
      - postgres
    image: adminer
    restart: always
    ports:
      - 8080:8080

  etms-client:
    build:
      context: ./client
    ports:
    - 7777:7777

  etms:
    hostname: etms.prod
    depends_on:
      - postgres
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: db.etms.dev
      POSTGRES_DB: etms
    ports:
      - 3000:3000
    volumes:
      - ./server/src:/home/node/src